global:
  scrape_interval: 5s  # How often to scrape targets

scrape_configs:
  - job_name: "fastapi-app"
    static_configs:
      - targets: ["fastapi_app:9000"]

  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "vllm_server"
    static_configs:
      - targets: ["vllm:8000"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "dcgm"
    static_configs:
      - targets: ["dcgm-exporter:9400"]
